version: '3.7'
services:
  frontend:
    networks:
      - network
    build: 
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /usr/src/app/node_modules
      - ./front:/usr/src/app
    stdin_open: true

  nginx:
    networks:
      - network
    volumes:
      - ./backend/media:/data/media
    restart: always
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - network
    volumes:
      - ./backend:/djangoproject
    command: >
      bash -c "
      python3 manage.py migrate&& 
      gunicorn backend.wsgi -b 0.0.0.0:8000"
    ports:
      - "8000:8000"
    expose:
      - "8000"
    container_name: app_backend

networks:
  network:


volumes:
  mariadb-database: