wandb_version: 1

model:
  desc: null
  value: Rec-VAE
batch_size:
  desc: null
  value: 500
lr:
  desc: null
  value: 0.0005
epochs:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1687240960.217372
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 16
      - 17
      - 23
      - 37
      4: 3.10.11
      5: 0.15.4
      8:
      - 3
      - 5
